<a href="https://colab.research.google.com/github/OMatheusWander/CienciadeDadosUFSC/blob/Estat%C3%ADstica-Aplicada-I/Aula_2_Estat%C3%ADstica_Aplicada_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
set.seed(2026)

runif(1)

[1] 0.6986735

In [19]:
genero = sample(c("Feminino", "Masculino"), size = 10000, replace= T, prob = c(0.2, 0.8))

table(genero)

genero
 Feminino Masculino
     1988      8012

In [24]:
sangue = sample(c("A", "B", "AB", "O"), size = 10000, replace= T, prob = c(0.4, 0.11, 0.04, 0.45))

table(sangue)

sangue
   A   AB    B    O
3943  416 1106 4535

In [26]:
residencia = sample(paste("Residência",1: 2500),
             size= 10000,
             replace = T)

max(table(residencia))
min(table(residencia))

table(table(residencia))

[1] 13

[1] 1

  1   2   3   4   5   6   7   8   9  10  11  13
190 366 491 486 390 248 152  81  35  15   3   1

In [28]:
renda = numeric(1000)

renda[genero == "Masculino"] = rexp(sum(genero == "Masculino"), rate = 1/4000)

renda[genero == "Feminino"] = rexp(sum(genero == "Feminino"), rate = 1/4000)


dados = data.frame(genero, sangue, residencia, renda)

str(dados)
dim(dados)
head(dados)
tail(dados)

'data.frame':	10000 obs. of  4 variables:
 $ genero    : chr  "Masculino" "Masculino" "Masculino" "Masculino" ...
 $ sangue    : chr  "A" "A" "O" "A" ...
 $ residencia: chr  "Residência 2322" "Residência 1761" "Residência 317" "Residência 170" ...
 $ renda     : num  16829 5444 368 1141 1996 ...

[1] 10000     4

  genero    sangue residencia      renda
1 Masculino A      Residência 2322 16828.6526
2 Masculino A      Residência 1761  5444.2335
3 Masculino O      Residência 317    368.4744
4 Masculino A      Residência 170   1140.7875
5 Masculino B      Residência 185   1996.1136
6 Masculino A      Residência 1679 12129.3466

      genero    sangue residencia      renda
9995  Masculino A      Residência 1180  3098.4992
9996  Feminino  O      Residência 1070  6368.3051
9997  Masculino O      Residência 1930   576.5545
9998  Masculino O      Residência 1217  2605.3100
9999  Masculino O      Residência 2245 10076.5346
10000 Feminino  O      Residência 803   4576.7100

In [39]:
#Amostra Aleatória Simples

library(dplyr)
sample_n(dados,10)

#Amostra Estratificada

?slice_sample(dados,)


slice_sample( dados(genero == "Masculino"))

   genero    sangue residencia      renda
1  Masculino O      Residência 1485 3615.1812
2  Masculino B      Residência 2420  956.0627
3  Masculino O      Residência 201  6438.3079
4  Masculino A      Residência 2161 2076.8219
5  Masculino O      Residência 1541 6096.1000
6  Masculino A      Residência 1872  449.9345
7  Masculino AB     Residência 1528  651.1817
8  Feminino  A      Residência 1032 3827.7471
9  Feminino  O      Residência 2129 1772.9856
10 Feminino  AB     Residência 1895 6528.9227

ERROR: Error in dados(genero == "Masculino"): could not find function "dados"

In [51]:
dados |>
  filter(sangue == "A") |>
  slice_sample(n = 5 ) # Seleciona 1 linha aleatória (exemplo)

  genero    sangue residencia      renda
1 Masculino A      Residência 1687 5068.1043
2 Masculino A      Residência 1095  107.6839
3 Masculino A      Residência 561   912.2788
4 Masculino A      Residência 2219 4491.7968
5 Masculino A      Residência 25   2457.4108

In [56]:
dadosm = dados[genero == "Masculino",]
dadosf = dados[genero == "Feminino",]

sample_n(dadosm,8)
sample_n(dadosf,2)

  genero    sangue residencia      renda
1 Masculino A      Residência 1316 3605.4890
2 Masculino AB     Residência 482  3371.3462
3 Masculino O      Residência 1233 9367.3744
4 Masculino B      Residência 1819 2977.5564
5 Masculino AB     Residência 2045 1384.7773
6 Masculino B      Residência 1423 2233.6448
7 Masculino A      Residência 1081  154.8751
8 Masculino O      Residência 939  2057.5398

  genero   sangue residencia     renda
1 Feminino B      Residência 144   308.3535
2 Feminino O      Residência 496 10222.6412

In [78]:
#Amostra por Conglomerado

res_sorteadas = sample(unique(dados$residencia), 10)
res_sorteadas

 [1] "Residência 2069" "Residência 12"   "Residência 1535" "Residência 1733"
 [5] "Residência 620"  "Residência 239"  "Residência 1447" "Residência 708"
 [9] "Residência 40"   "Residência 1642"

In [82]:
dados[dados$residencia %in% res_sorteadas,]

     genero    sangue residencia      renda
254  Masculino A      Residência 1535  1262.62234
450  Feminino  O      Residência 708   2245.24763
762  Masculino O      Residência 708    247.98045
869  Masculino O      Residência 1447  1230.87336
872  Masculino AB     Residência 620   2017.16737
1876 Masculino O      Residência 239   2087.27444
2097 Feminino  O      Residência 12   14814.25830
2481 Feminino  A      Residência 40    8545.58557
2650 Masculino A      Residência 2069   912.74819
2763 Masculino A      Residência 1642  2559.17134
2892 Masculino O      Residência 1535  7829.68243
3255 Masculino O      Residência 12    5592.48353
3330 Feminino  O      Residência 239  12069.18067
3397 Feminino  B      Residência 12    1114.53463
3512 Masculino O      Residência 12    7961.38558
3873 Masculino A      Residência 239   3613.75634
4367 Masculino B      Residência 40    8296.78554
4457 Masculino A      Residência 708  10360.14159
5259 Masculino A      Residência 620   2123.88439
5675 Masculino A      Residência 12    4088.75481
5701 Masculino A      Residência 2069  2177.77820
5802 Masculino A      Residência 620   6125.33021
5884 Masculino AB     Residência 40    9571.84108
6158 Masculino A      Residência 40      40.77116
6247 Masculino O      Residência 1447    77.64048
6259 Masculino O      Residência 1733  8230.78805
6819 Masculino O      Residência 40    7821.78336
6897 Masculino A      Residência 2069   154.39259
6989 Masculino A      Residência 2069  4223.62327
7299 Masculino O      Residência 1535  2337.18310
7451 Masculino A      Residência 708    186.32468
7883 Masculino O      Residência 40    9953.74718
7922 Masculino A      Residência 1733  3066.63667
8201 Masculino A      Residência 40    2383.51845
8987 Masculino O      Residência 1447   563.43397
9254 Masculino A      Residência 12    1190.08443
9540 Masculino A      Residência 239  11189.20606
9558 Masculino B      Residência 12    9272.92006
9866 Masculino AB     Residência 1447   131.78922